apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: airflow-static-ip
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - secretName: airflow-tls
    hosts:
    - web.{{ .Values.domain }}
    - flower.{{ .Values.domain }}
  rules:
  - host: web.{{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 8080
  - host: flower.{{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: flower
          servicePort: 5555
